<br><br><B>Consider the below code to answer further questions:</B>

In [7]:
import numpy as np

list_ = ['1','2','3','4','5']

array_list = np.array(object = list_)

<B>Q1. Is there any difference in the data type of variables list_ and array_list? If there is then write a code
to print the data types of both the variables.</B>

Yes there is difference between data types of variable list_ and array_list. list_ is a Python list variable where as array_list is a Numpy variable created from list_ 

In [8]:
import numpy as np

list_ = ['1', '2', '3', '4', '5']
array_list = np.array(object=list_)

# Check the data types
print(f'Data type of list_: {type(list_)}')
print(f'Data type of array_list: {type(array_list)}')


Data type of list_: <class 'list'>
Data type of array_list: <class 'numpy.ndarray'>


<br><br><B>Q2. Write a code to print the data type of each and every element of both the variables list_ and
arra_list.</B>

In [10]:
import numpy as np

list_ = ['1', '2', '3', '4', '5']
array_list = np.array(object=list_)

# Print data type of each element
for x in list_:
    print(f'Data type of element in list_: {type(x)}')

for x in array_list:
    print(f'Data type of element in array_list: {type(x)}')


Data type of element in list_: <class 'str'>
Data type of element in list_: <class 'str'>
Data type of element in list_: <class 'str'>
Data type of element in list_: <class 'str'>
Data type of element in list_: <class 'str'>
Data type of element in array_list: <class 'numpy.str_'>
Data type of element in array_list: <class 'numpy.str_'>
Data type of element in array_list: <class 'numpy.str_'>
Data type of element in array_list: <class 'numpy.str_'>
Data type of element in array_list: <class 'numpy.str_'>


<br><br><br><B>Q3. Considering the following changes in the variable, array_list:<br>
array_list = np.array(object = list_, dtype = int)</B><br><br>
Will there be any difference in the data type of the elements present in both the variables, list_ and
arra_list? If so then print the data types of each and every element present in both the variables, list_
and arra_list.

In [12]:
import numpy as np

list_ = ['1', '2', '3', '4', '5']
array_list = np.array(object=list_, dtype=int)

# Print data type of each element after the change in array_list
for element in list_:
    print(f'Data type of element in list_: {type(element)}')

for element in array_list:
    print(f'Data type of element in array_list: {type(element)}')


Data type of element in list_: <class 'str'>
Data type of element in list_: <class 'str'>
Data type of element in list_: <class 'str'>
Data type of element in list_: <class 'str'>
Data type of element in list_: <class 'str'>
Data type of element in array_list: <class 'numpy.int64'>
Data type of element in array_list: <class 'numpy.int64'>
Data type of element in array_list: <class 'numpy.int64'>
Data type of element in array_list: <class 'numpy.int64'>
Data type of element in array_list: <class 'numpy.int64'>


<br><br><br><B>Consider the below code to answer further questions:<br></B>
import numpy as np<br>
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]<br>
num_array = np.array(object = num_list)

<B>Q4. Write a code to find the following characteristics of variable, num_array:<br></B>
(i) shape<br>
(ii) size

In [15]:
import numpy as np
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)
#shape of num_array
print(f"shape of num_array", num_array.shape)
#size of num_array
print(f"size of num_array", num_array.size)

shape of num_array (2, 3)
size of num_array 6


<br><br><B>Q5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array
creation function.</B><br>[Hint: The size of the array will be 9 and the shape will be (3,3).]

In [18]:
import numpy as np
data=np.random.randint(0,1,(3,3))
print(data)
print(data.size)
print(data.shape)

[[0 0 0]
 [0 0 0]
 [0 0 0]]
9
(3, 3)



<br><br><B>
Q6. Create an identity matrix of shape (5,5) using numpy functions?<br></B>
[Hint: An identity matrix is a matrix containing 1 diagonally and other elements will be 0.]

In [21]:
import numpy as np
data1=np.diag([1,1,1,1,1,])
print(data1)

[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]
